apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    env: deploy
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prometheus-pvc

spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus
    labels:
      env: deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
       env: deploy
  template:
    metadata:
     name: prometheus-pod
     labels:
       env: deploy
    spec: 
      containers:
        - name: promcont1
          image: yashwanth3/prometheus:x2
          volumeMounts:
            - name: logs
              mountPath: /yashprom
          volumeMounts:
            - name: ymlnodes
              mountPath: /yashprom/prometheus.yml
              subPath: prometheus.yml
      volumes:
      - name: logs
        persistentVolumeClaim:
            claimName: prometheus-pvc
      - name: ymlnodes
        configMap:
            name: prometheus-nodes
            defaultMode: 0744	